// export {default as AdminLayouts} from './AdminLayouts'
export {default as HomeLayouts} from './HomeLayouts'
export {default as ProfileLayouts} from './profile'
export {default as Auth} from './auth'
// export {default as CheckOutLayouts} from './CheckOutLayouts'